apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---

apiVersion: elasticweb.com.alibaba-inc.chenyi/v1
kind: ElasticWeb
metadata:
  namespace: dev
  name: elasticweb-sample
spec:
  # Add fields here
#  image: tomcat:8.0.18-jre8
  image: fabric8/tomcat-8
  port: 30003
  singlePodQPS: 500
  totalQPS: 600

